# Generated by Django 4.2 on 2023-05-05 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("exercises", "0002_alter_author_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="email",
            field=models.EmailField(max_length=254, null=True, verbose_name="e-mail"),
        ),
        migrations.AlterField(
            model_name="book",
            name="classification",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercises",
                to="exercises.classification",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="publisher",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercises",
                to="exercises.publisher",
            ),
        ),
    ]
